A:
  size: 5
  point0:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
  point1:
    x: 1
    y: 1
    z: 2
    roll: 1
    pitch: 1
    yaw: 1
  point2:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
  point3:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
  point4:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
B:
  size: 5
  point0:
    x: 1
    y: 1
    z: 1.234
    roll: 1
    pitch: 1
    yaw: 1
  point1:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
  point2:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
  point3:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1
  point4:
    x: 1
    y: 1
    z: 1
    roll: 1
    pitch: 1
    yaw: 1